// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from "typesafe-i18n"

export type BaseTranslation = BaseTranslationType
export type BaseLocale = "en-US"

export type Locales = "en-US" | "zh-Hans"

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
  /**
   * T​e​s​t​i​n​g​ ​P​l​u​g​i​n
   */
  PLUGIN_DISPLAY_NAME: string
  /**
   * A​ ​p​l​u​g​i​n​ ​f​o​r​ ​t​e​s​t​i​n​g​ ​t​h​e​ ​p​l​u​g​i​n
   */
  PLUGIN_DESCRIPTION: string
  /**
   * C​r​e​d​e​n​t​i​a​l​ ​D​i​s​p​l​a​y​ ​N​a​m​e
   */
  CREDENTIAL_DISPLAY_NAME: string
  /**
   * A​ ​c​r​e​d​e​n​t​i​a​l​ ​f​o​r​ ​t​h​e​ ​p​l​u​g​i​n
   */
  CREDENTIAL_DESCRIPTION: string
  /**
   * T​e​s​t​i​n​g​ ​T​o​o​l
   */
  TESTING_TOOL_DISPLAY_NAME: string
  /**
   * A​ ​t​o​o​l​ ​f​o​r​ ​t​e​s​t​i​n​g​ ​t​h​e​ ​p​l​u​g​i​n
   */
  TESTING_TOOL_DESCRIPTION: string
  /**
   * L​o​c​a​t​i​o​n
   */
  LOCATION_DISPLAY_NAME: string
  /**
   * T​h​e​ ​l​o​c​a​t​i​o​n​ ​t​o​ ​t​e​s​t
   */
  LOCATION_HINT: string
  /**
   * E​n​t​e​r​ ​t​h​e​ ​l​o​c​a​t​i​o​n​ ​t​o​ ​t​e​s​t
   */
  LOCATION_PLACEHOLDER: string
  /**
   * A​P​I​ ​K​e​y
   */
  API_KEY_DISPLAY_NAME: string
  /**
   * T​h​e​ ​A​P​I​ ​k​e​y​ ​t​o​ ​u​s​e​ ​f​o​r​ ​t​h​e​ ​p​l​u​g​i​n
   */
  API_KEY_HINT: string
  /**
   * S​e​l​e​c​t​ ​t​h​e​ ​A​P​I​ ​k​e​y​ ​t​o​ ​u​s​e​ ​f​o​r​ ​t​h​e​ ​p​l​u​g​i​n
   */
  API_KEY_PLACEHOLDER: string
}

export type TranslationFunctions = {
  /**
   * Testing Plugin
   */
  PLUGIN_DISPLAY_NAME: () => LocalizedString
  /**
   * A plugin for testing the plugin
   */
  PLUGIN_DESCRIPTION: () => LocalizedString
  /**
   * Credential Display Name
   */
  CREDENTIAL_DISPLAY_NAME: () => LocalizedString
  /**
   * A credential for the plugin
   */
  CREDENTIAL_DESCRIPTION: () => LocalizedString
  /**
   * Testing Tool
   */
  TESTING_TOOL_DISPLAY_NAME: () => LocalizedString
  /**
   * A tool for testing the plugin
   */
  TESTING_TOOL_DESCRIPTION: () => LocalizedString
  /**
   * Location
   */
  LOCATION_DISPLAY_NAME: () => LocalizedString
  /**
   * The location to test
   */
  LOCATION_HINT: () => LocalizedString
  /**
   * Enter the location to test
   */
  LOCATION_PLACEHOLDER: () => LocalizedString
  /**
   * API Key
   */
  API_KEY_DISPLAY_NAME: () => LocalizedString
  /**
   * The API key to use for the plugin
   */
  API_KEY_HINT: () => LocalizedString
  /**
   * Select the API key to use for the plugin
   */
  API_KEY_PLACEHOLDER: () => LocalizedString
}

export type Formatters = {}
